defaults:
  - _self_


name: dino
finetune: /data/RSP/dino_kinetics/checkpoint-199.pth
weight_decay: 0
num_classes: ${dataset.nb_classes}

model_kwargs:
  _target_: timm.models.vision_transformer.vit_small_patch16_224

