defaults:
  - _self_


name: mae
finetune: /data/RSP/mae_kinetics/checkpoint-199.pth
global_pool: false
cls_token: true
weight_decay: 0
num_classes: ${dataset.nb_classes}

model_kwargs:
  _target_: timm.models.vision_transformer.vit_small_patch16_224