from modeling import (
    models_rsp,
    models_rsp_caption,
    models_mse,
    models_context_in_posterior,
    models_cos,
    models_mse_reg,
    models_joint_emb,
    models_joint_emb_cut,
    models_mse_implicit,
    models_joint_text_q,
    models_joint_m3ae, models_joint_m3ae_implicit, models_joint_implicit, models_joint_implicit_scale
)

# Original RSP models
rsp_vit_small_patch8 = models_rsp.rsp_vit_small_patch8_dec512d8b
rsp_vit_small_patch16 = models_rsp.rsp_vit_small_patch16_dec512d8b
rsp_vit_base_patch16 = models_rsp.rsp_vit_base_patch16_dec512d8b
rsp_vit_large_patch16 = models_rsp.rsp_vit_large_patch16_dec512d8b

# Caption models
rsp_vit_small_patch8_caption = models_rsp_caption.rsp_vit_small_patch8_dec512d8b
rsp_vit_small_patch16_caption = models_rsp_caption.rsp_vit_small_patch16_dec512d8b
rsp_vit_base_patch16_caption = models_rsp_caption.rsp_vit_base_patch16_dec512d8b
rsp_vit_large_patch16_caption = models_rsp_caption.rsp_vit_large_patch16_dec512d8b

# MSE variants
rsp_mse_vit_small_patch8 = models_mse.rsp_mse_vit_small_patch8_dec512d8b
rsp_mse_vit_small_patch16 = models_mse.rsp_mse_vit_small_patch16_dec512d8b
rsp_mse_vit_base_patch16 = models_mse.rsp_mse_vit_base_patch16_dec512d8b
rsp_mse_vit_large_patch16 = models_mse.rsp_mse_vit_large_patch16_dec512d8b

rsp_context_in_posterior_vit_small_patch8 = models_context_in_posterior.rsp_context_in_post_small_patch8_dec512d8b
rsp_context_in_posterior_vit_small_patch16 = models_context_in_posterior.rsp_context_in_post_small_patch16_dec512d8b
rsp_context_in_posterior_vit_base_patch16 = models_context_in_posterior.rsp_context_in_post_base_patch16_dec512d8b
rsp_context_in_posterior_vit_large_patch16 = models_context_in_posterior.rsp_context_in_post_large_patch16_dec512d8b

rsp_cos_vit_small_patch8 = models_cos.rsp_cos_vit_small_patch8_dec512d8b
rsp_cos_vit_small_patch16 = models_cos.rsp_cos_vit_small_patch16_dec512d8b
rsp_cos_vit_base_patch16 = models_cos.rsp_cos_vit_base_patch16_dec512d8b
rsp_cos_vit_large_patch16 = models_cos.rsp_cos_vit_large_patch16_dec512d8b

rsp_mse_reg_vit_small_patch8 = models_mse_reg.rsp_mse_reg_vit_small_patch8_dec512d8b
rsp_mse_reg_vit_small_patch16 = models_mse_reg.rsp_mse_reg_vit_small_patch16_dec512d8b
rsp_mse_reg_vit_base_patch16 = models_mse_reg.rsp_mse_reg_vit_base_patch16_dec512d8b
rsp_mse_reg_vit_large_patch16 = models_mse_reg.rsp_mse_reg_vit_large_patch16_dec512d8b

rsp_cos_joint_vit_small_patch8 = models_joint_emb.rsp_cos_joint_vit_small_patch8_dec512d8b
rsp_cos_joint_vit_small_patch16 = models_joint_emb.rsp_cos_joint_vit_small_patch16_dec512d8b
rsp_cos_joint_vit_base_patch16 = models_joint_emb.rsp_cos_joint_vit_base_patch16_dec512d8b
rsp_cos_joint_vit_large_patch16 = models_joint_emb.rsp_cos_joint_vit_large_patch16_dec512d8b

rsp_cos_joint_cut_vit_small_patch16 = models_joint_emb_cut.rsp_cos_joint_cut_vit_small_patch16

rsp_mse_implicit_vit_small_patch16 = models_mse_implicit.rsp_mse_implicit_vit_small_patch16_dec512d8b

rsp_joint_text_qvit_small_patch16 = models_joint_text_q.rsp_joint_text_qvit_small_patch16_dec512d8b

rsp_joint_m3ae_vit_small_patch16 = models_joint_m3ae.rsp_joint_m3ae_vit_small_patch16_dec512d8b

rsp_joint_m3ae_implicit_vit_small_patch16 = models_joint_m3ae_implicit.rsp_joint_m3ae_implicit_vit_small_patch16_dec512d8b

rsp_joint_implicit_vit_small_patch16 = models_joint_implicit.rsp_joint_implicit_vit_small_patch16_dec512d8b

rsp_joint_implicit_scale_vit_small_patch16 = models_joint_implicit_scale.rsp_joint_implicit_scale_vit_small_patch16_dec512d8b

rsp_joint_cos_online_vit_small_patch16 = models_joint_cos_online.rsp_joint_cos_online_vit_small_patch16_dec512d8b