defaults:
  - main
  - _self_

exp_name: bridge_caption_joint_cos

model_name: rsp_cos_joint_cut_vit_small_patch16

dataset:
  _target_: dataset.bridge_caption.BridgeCaption
  data_dir: /shared/sjw_alinlab/RSP/npy_dataset

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_online
  _partial_: true

num_workers: 4
batch_size: 48
accum_iter: 8

model_params:
  cos_scale: 1.0
  
