defaults:
  - _self_

# Training parameters
batch_size: 64
epochs: 400
accum_iter: 1
device: "cuda"
seed: 0
resume: ""
start_epoch: 0
output_dir: "./output_dir"
log_dir: "./output_dir"

# Model parameters
model: "rsp_vit_small_patch16"
input_size: 224
norm_pix_loss: false
mask_ratio: 0.75
noise_scale: 0.5
kl_scale: 0.01
kl_balance: 0.2
kl_freebit: 0.1
stoch: 32
discrete: 32

# Optimizer parameters
weight_decay: 0.05
lr: null
blr: 1.5e-4
min_lr: 0.0
warmup_epochs: 40

# Dataset parameters
data_path: "/data/kinetics400"
max_distance: 48
repeated_sampling: 2
num_workers: 6
pin_mem: true
prefetch_factor: 2

# Distributed training parameters
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: "env://"
