defaults:
  - main
  - _self_

exp_name: rsp_context_in_post

model_name: rsp_context_in_posterior_vit_small_patch16

data_root: /root

dataset:
  _target_: util.kinetics_caption.PairedKineticsWithCaption
  frame_root: ${..data_root}/kinetics400caption/frames
  frame_info_path: ${..data_root}/kinetics400caption/frame_info.json
  embeddings_path: ${..data_root}/kinetics400caption/embeddings.jsonl

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_llm
  _partial_: true

model_params:
  kl_scale: 0.001
  enable_rms_norm: true
  embed_scale_factor: 1.0