defaults:
  - main
  - _self_

exp_name: context_in_post_video_label

model_name: rsp_context_in_posterior_vit_small_patch16

data_root: /data

dataset:
  _target_: util.kinetics_caption_video_label.PairedKineticsCaptionVideoLabel
  frame_root: ${..data_root}/kinetics400caption
  frame_info_path: ${..data_root}/kinetics400caption/frame_info.json
  class_embeddings_path: ${..data_root}/kinetics400caption/class_embeddings.json
  frame_info_additional_path: ${..data_root}/kinetics400caption/frame_info_additional.json


train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_llm
  _partial_: true

num_workers: 4
batch_size: 24
accum_iter: 8

model_params:
  enable_rms_norm: False
  
