defaults:
  - main
  - _self_

exp_name: rsp_cos_cut_8_pair

model_name: rsp_cos_joint_cut_vit_small_patch16

data_root: /data

dataset:
  _target_: util.kinetics_caption_8_pair.PairedKineticsWithCaption8Pair
  frame_root: ${..data_root}/kinetics400caption8
  frame_info_path: ${..data_root}/kinetics400caption8/frame_info.json
  embeddings_path: ${..data_root}/kinetics400caption8/embedding_large_512.jsonl
  frame_info_additional_path: ${..data_root}/kinetics400caption8/frame_info_additional.json
  embeddings_additional_path: ${..data_root}/kinetics400caption8/embedding_6_pair_512.jsonl

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_llm
  _partial_: true

num_workers: 4
batch_size: 24
accum_iter: 8
pin_memory: false
prefetch_factor: 3

model_params:
  context_emb_dim: 3072
  embed_decoder_num_heads: 8
  embed_decoder_depth: 4
  kl_scale: 0.005
  cos_scale: 0.1

