defaults:
  - main
  - _self_

exp_name: rsp_mse_global_caption

model_name: rsp_joint_implicit_vit_small_patch16

dataset:
  _target_: util.kinetics_global_caption.PairedKineticsWithGlobalCaption
  video_root: /data/kinetics400
  frame_info_path: /data/kinetics400caption/global_frame.json
  embeddings_path: /data/kinetics400caption/global_embedding.jsonl
  repeated_sampling: 2
  max_distance: 48
  seed: 42

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_llm
  _partial_: true

mse_scale: 0.1
num_workers: 1

model_params:
  enable_rms_norm: true
