defaults:
  - main
  - _self_

exp_name: rsp_cos_cut_8_pair

model_name: rsp_joint_implicit_scale_vit_small_patch16

data_root: /data

dataset:
  _target_: util.precomputed_caption_dataset.PrecomputedCaptionDataset
  dataset_file: /data/rlwrld-common/junyoon/rlbench_64_caption/captions_final.json
  data_root: /data/rlwrld-common/junyoon/rlbench_demo
  repeated_sampling: 2
  max_pair_pool: 32

embedding_model:
  name: "Alibaba-NLP/gte-base-en-v1.5"
  max_length: 2048
  device: "cuda"
  tokenizer_name: "Alibaba-NLP/gte-base-en-v1.5"

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_online
  _partial_: true

num_workers: 4
batch_size: 24
accum_iter: 8
pin_memory: false
prefetch_factor: 3

model_params:
  context_emb_dim: 3072
  embed_decoder_num_heads: 8
  embed_decoder_depth: 4
  kl_scale: 0.005
  cos_scale: 0.1

