defaults:
  - main
  - _self_

exp_name: rsp_joint_self

model_name: rsp_joint_self_vit_small_patch16

data_root: /data

dataset:
  _target_: dataset.bridge_caption_self.BridgeCaptionSelf
  data_dir: ${..data_root}/bridge_caption_self
  repeated_sampling: 2
  interval: 4
  seed: 42

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_general
  _partial_: true

num_workers: 4
batch_size: 24
accum_iter: 8

model_params:
  context_emb_dim: 768
  embed_decoder_num_heads: 8
  embed_decoder_depth: 4
  kl_scale: 0.005
  cos_scale: 0.1
