defaults:
  - main
  - _self_

exp_name: kinetics_fixed

dataset:
  _target_: util.kinetics.PairedKineticsFixed
  root: ${oc.env:HOME}/RSP/artifacts/kinetics
  max_distance: ${max_distance}
  repeated_sampling: ${repeated_sampling}

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_fixed
  _partial_: true
