defaults:
  - main
  - _self_

exp_name: rsp_fixed

model_name: rsp_vit_small_patch16

dataset:
  _target_: util.kinetics_fixed.PairedKineticsFixed
  root: /data/kinetics400

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch
  _partial_: true
