defaults:
  - main
  - _self_

exp_name: rsp_kinetics_online_caption

model_name: rsp_caption_vit_small_patch16

data_root: /root

dataset:
  _target_: util.kinetics_online_caption.RLBenchOnlineCaption
  root: ${..data_root}/kinetics400caption
  max_distance: 48
  repeated_sampling: 2
  llm:
    model: "OpenGVLab/InternVL2_5-8B"
    host: "0.0.0.0"
    port: 23333
    postfix: "/v1/chat/completions"

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_online
  _partial_: true

embedding_model:
  name: "Alibaba-NLP/gte-base-en-v1.5"
  max_length: 8192
  device: "cuda"
  tokenizer_name: "Alibaba-NLP/gte-base-en-v1.5"

model_params:
  kl_scale: 0.001
  enable_rms_norm: false
  embed_scale_factor: 1.0
