defaults:
  - main
  - _self_

exp_name: kinetics_caption

dataset:
  _target_: util.kinetics_caption.PairedKineticsWithCaption
  data_path: ${oc.env:HOME}/RSP/artifacts/frame_analysis_results_complete.json
  embeddings_path: ${oc.env:HOME}/RSP/artifacts/combined_output.jsonl
  repeated_sampling: ${repeated_sampling}

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_llm
  _partial_: true
