defaults:
  - _self_

# Distributed training
dist_on_itp: False
dist_url: "env://"
world_size: 1
gpu: 0
rank: -1
distributed: True
device: "cuda"

# Training parameters
batch_size: 512
epochs: 90
accum_iter: 1
num_workers: 10
pin_memory: True
output_dir: "output/linear_probe"
use_wandb: True
project_name: "mae-linear-probe"
run_name: "kinetics400"

# Model parameters
model_name: "vit_large_patch16"
model:
  num_classes: 400
  global_pool: False

# Optimizer parameters
lr: 0.1
weight_decay: 0
warmup_epochs: 10
min_lr: 0.0

# Dataset parameters
train_dataset:
  _target_: eval.action.datasets.kinetics400.Kinetics400
  data_root: "/path/to/kinetics400"
  split: "train"
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.RandomResizedCrop
        size: 224
        interpolation: 3
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

val_dataset:
  _target_: eval.action.datasets.kinetics400.Kinetics400
  data_root: "/path/to/kinetics400"
  split: "val"
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: 256
        interpolation: 3
      - _target_: torchvision.transforms.CenterCrop
        size: 224
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

# Checkpoint
checkpoint_path: "/path/to/checkpoint.pth"
