defaults:
  - main
  - _self_

exp_name: rsp_m3ae_no_cosloss

model_name: rsp_joint_m3ae_implicit_vit_small_patch16

data_root: /data

dataset:
  _target_: util.kinetics_m3ae.MemmapPairedKineticsDataset
  memmap_dir: /data/memmap_data/
  # frame_root: ${..data_root}/kinetics400caption
  # frame_info_path: ${..data_root}/kinetics400caption/frame_info.json
  # embeddings_path: ${..data_root}/kinetics400caption/embedding_large_512.jsonl
  # future_embeddings_path: ${..data_root}/kinetics400caption/future_embedding_fixed.jsonl
  # frame_info_additional_path: ${..data_root}/kinetics400caption/frame_info_additional.json
  # embeddings_additional_path: ${..data_root}/kinetics400caption/embedding_6_pair_512.jsonl

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_m3ae
  _partial_: true

num_workers: 3
batch_size: 24
accum_iter: 8
pin_mem: True
prefetch_factor: 2

model_params:
  context_emb_dim: 3072
  embed_decoder_num_heads: 8
  embed_decoder_depth: 4
  kl_scale: 0.005
  cos_scale: 0.1


wandb:
  mode: "offline"  # Set to "disabled" to turn off wandb logging