defaults:
  - main
  - _self_

exp_name: rsp_mse

model_name: rsp_mse_vit_small_patch16

dataset:
  _target_: util.kinetics_caption.PairedKineticsWithCaption
  frame_root: /home/ubuntu/kinetics400caption/frames
  frame_info_path: /home/ubuntu/kinetics400caption/frame_info.json
  embeddings_path: /home/ubuntu/kinetics400caption/embeddings.jsonl

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_llm
  _partial_: true

num_workers: 2

model_params:
  kl_scale: 0.01
  mse_scale: 0.1
  enable_rms_norm: true
  embed_scale_factor: 1.0

