defaults:
  - main
  - _self_

exp_name: rsp_kinetics_online_caption

model_name: rsp_joint_implicit_vit_small_patch16

data_root: /data/RSP/rlbench/demo

dataset:
  _target_: util.kinetics_online_caption.RLBenchOnlineCaption
  root: ${..data_root}
  max_distance: 48
  repeated_sampling: 2
  llm:
    model: "OpenGVLab/InternVL2_5-8B"
    host: "0.0.0.0"
    port: 23333
    postfix: "/v1/chat/completions"
  embedding_model: ${..embedding_model.name}

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch_online
  _partial_: true

embedding_model:
  name: "Alibaba-NLP/gte-base-en-v1.5"
  max_length: 2048
  device: "cuda"
  tokenizer_name: "Alibaba-NLP/gte-base-en-v1.5"

model_params:
  context_emb_dim: 768
  embed_decoder_num_heads: 8
  embed_decoder_depth: 4
  kl_scale: 0.005
  cos_scale: 0.1
