defaults:
  - main
  - _self_

exp_name: rlbench_rsp

model_name: rsp_vit_small_patch16

dataset:
  _target_: util.rlbench.PairedRLBench
  root: /data/RSP/rlbench/demo

train_loop:
  _target_: engine_pretrain_repsamp.train_one_epoch
  _partial_: true

kl_scale: 0.001